wordpress:
  wordpressPassword: foo
  mariadb:
    db:
      password: bar
    rootUser:
      password: baz

dev: false
prod: false

# repositories:
#   name: registry
#   url: https://charts.helm.sh/stable