wordpress:
  wordpressPassword: foo
  mariadb:
    db:
      password: bar
    rootUser:
      password: baz

dev: true
prod: false

dependencies:
- name: wordpress
  repository: https://charts.helm.sh/stable